### ISSUE TITLE
Invitation email link does not redirect to appv3

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#102]
I received an invite for a collaboration group, with a link that did NOT redirect to appv3:

https://test.beep.nl/webapp#!/groups/55/token/7jI5BLAXT8XpBLAcKuWuusBLA

Could you please make it redirect to v3?

**Comment by pvgennip** [comment]
@JuliaBD What should be the URL? It should now redirect to https://appv3.beep.nl/sign-in

**Comment by pvgennip** [comment]
Solved on test
