### ISSUE TITLE
adding new group member gives 500 error

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#103]
Adding new group member gives 500 "server error", no invitation email is sent. Invitation does appear in the app, for the newly invited user. + invitation date appears in the edited group, when re-opened.

**Comment by JuliaBD** [comment]
As this started happening recently, maybe it is related to fixing the invitation email link? https://github.com/beepnl/BEEP/issues/102

**Comment by pvgennip** [comment]
Issue should be fixed on test
