### ISSUE TITLE
userlocale patch request gives 500 error

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#104]
/api/userlocale PATCH, with payload: {email: "julia@bla.nl", locale: "nl"}
gives 500 error 'user_not_edited'. After a hard page refresh it still occurs, other API calls are working

**Comment by JuliaBD** [comment]
Can't replicate this now... close for now and keep an eye on it? @pvgennip

**Comment by pvgennip** [comment]
Does not occur anymore
