### ISSUE TITLE
alertrule from other user triggers alerts in my account

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#105]
Alertrule 36 "BEEP base battery high', which is NOT a default rule, made by/for user BEEP1 triggers alerts in my BEEP test account for 'Kast v3'.

The alertrule can't be edited as it is not returned by the GET alert-rules call (and rightfully so)

Somewhere in the alerts flow a user id check must be missing? Or the alertrule has not been saved correctly?

**Comment by JuliaBD** [comment]
In addition: alert seems to be triggered every 2 hours, whilst the resolution is 15 minutes (and the rule should validate every time), but that probably is a separate issue?

**Comment by pvgennip** [comment]
AlertRules should only be triggered for your own user now
