### ISSUE TITLE
Log feeding_box & queen_excluder layer in hive action inspection

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#109]
In v3 when placing a feeding box and queen excluder, a hive action is added as an inspection, but this only mentions the number of brood and honey layers and frames (see screenshot). This is confusing as nothing happened with those layers.

Solution:
Feeding box and/or queen excluder should be added as inspection items for the 'hive action' inspection when adding or removing one or more of those layers.

Please note that there can now be multiple queen_excluder layers (and only 1 feeding box layer)

![Schermafbeelding 2021-06-01 om 14 46 49](https://user-images.githubusercontent.com/9794382/120326108-a6b4cc80-c2e8-11eb-9302-9e9d88474f79.png)

**Comment by pvgennip** [comment]
Added at test.beep.nl

**Comment by pvgennip** [comment]
Works for v2 app too
