### ISSUE TITLE
image upload size limit too low

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#113]
On live / v2 size limit for image upload (used for TPA) seems to be around 5Mb
On test / v3 size limit now seems to be around 1.5Mb

We'd like to increase this to 10Mb maybe? Or at least for v3 it should be back to 5Mb.

**Comment by pvgennip** [comment]
@JuliaBD The PHP settings for both servers are: 

- upload_max_filesize: 40MB
- post_max_size: 40 MB

The .env settings contain:

- IMAGE_RESIZE_PIXELS=5000 op test
- IMAGE_RESIZE_PIXELS=5000 op live

**Comment by pvgennip** [comment]
Image of 9MB tested: ok

**Comment by pvgennip** [comment]
Image of 14MB uploads.
Fixed linke from /public to storage/
