### ISSUE TITLE
All date/times in utc format

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#116]
For @pvgennip: make sure all terms are saved/returned in utc format. If timezone is present in header, use that together with the provided local date/time to convert to utc.

For @JuliaBD: make sure timezone is provided in header esp. when posting/patching a data/time var. And make sure all returned date/times are converted to users timezone when displayed.

**Comment by pvgennip** [comment]
Manual input (i.e. inspections/photos/apiary/device/hive/etc) would need the timezone header to store the time in UTC. It requires a lot of refactoring/adjustment/database transformations/roleout timing to get this done correctly

**Comment by JuliaBD** [comment]
Or, for devices and sensor definitions, keep it as is, as otherwise database values need to be updated?

**Comment by pvgennip** [comment]
All times at test.beep.nl are now in UTC.  date() was using Europe/Amsterdam time, now UTC (since config/app.php has UTC as default timezone)

**Comment by pvgennip** [comment]
@JuliaBD please check if all times are ok now

**Comment by JuliaBD** [comment]
Yes!
