### ISSUE TITLE
alert: update props

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#124]
-Make new props:
alert_display_value:
[quantity]: [value] + [unit]
If a new alert rule has been created it has value 'alert_rule_created'
alert_display_function: (separate prop because I want to show it on a new line)
[function summary] e.g.: 'Temperature < 35C'

-alert_value & alert_function props can then be deleted
-'alert_rule_deleted' alert can be deleted

**Comment by JuliaBD** [comment]
N.B.: If a new alert rule has been created, please make sure the alert_function has value 'alert_rule_created' @pvgennip

**Comment by pvgennip** [comment]
@JuliaBD Done
