### ISSUE TITLE
enable free period selection for /sensors/measurements GET request (add start & end parameter)

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#135]
Such that measurements of a period selected by the user (start & end date) can be returned when interval equals 'selection'.

Payload format example:
id=53&interval=selection&index=0&timeGroup=null&timezone=Europe/Amsterdam&start=2021-12-06%2000:00&end=2021-12-09%2023:59

Similar to HCS

**Comment by pvgennip** [comment]
Solved and added to test
