### ISSUE TITLE
Cannot update devices

### ISSUE THREAD

**Issue by georgevanvliet** [beepnl/BEEP#17]
After creating a device, using `POST https://test.beep.nl/api/devices/` I receive a JSON which contains the id of the new device.

The documentation mentions `PUT/PATCH https://test.beep.nl/api/devices/<id>`. When calling this endpoint with a json payload:
```
{"key":"<samekey>","name":"DifferentBaseName","hardware_id":"<samehardwareid>"}
```
, I get the error:
```
{
  "errors": {
    "key": [
      "The key has already been taken."
    ]
  }
}
```

When omitting the key, I get the error:
```
{
  "errors": {
    "key": [
      "The key field is required."
    ]
  }
}
```

**Comment by pvgennip** [comment]
Solved in branch add-data-export, commit a9b3fac
