### ISSUE TITLE
Listing sensor definitions gives a server error.

### ISSUE THREAD

**Issue by georgevanvliet** [beepnl/BEEP#18]
When calling `GET https://test.beep.nl/api/sensordefinition` I receive a 500 server error.

I think I have no definitions (can't check ;) so it might be a null pointer.

First part of error:
```
<!DOCTYPE html><!--


ErrorException: Trying to get property of non-object in file /opt/bitnami/apps/test.beep.nl/app/Http/Controllers/Api/SensorDefinitionController.php on line 74
Stack trace:
```

**Comment by pvgennip** [comment]
Fixed in commit 7e06a14 of branch add-data-export
