### ISSUE TITLE
hardware id is not stored when creating a new device

### ISSUE THREAD

**Issue by georgevanvliet** [beepnl/BEEP#19]
When executing `POST https://test.beep.nl/api/devices' with payload:

```
{"key":"fafafafafafafaf9","name":"MyBase","hardware_id":"0123456789abcdefffff"}
```

The `hardware_id` is not stored.
When writing the property as `hardwareId` it is also not stored.

**Comment by pvgennip** [comment]
Solved in branch add-data-export
