### ISSUE TITLE
Numerical Hive settings at apiary create are not limited to numbers

### ISSUE THREAD

**Issue by joostoftoday** [beepnl/BEEP#2]
Problem: When creating a new apiary, you can choose several options at the hive settings ("Hive amount at this location", "brood layers", etc.) These probably should be limited to numerical values, but the user can actually type in any value, like characters or special symbols.

**Comment by beepnl** [comment]
@joostoftoday Thanks for the indication. I'll put this in the backlog.

**Comment by pvgennip** [comment]
Solved in the current release
