### ISSUE TITLE
Change response for collection endpoints in case of empty collections

### ISSUE THREAD

**Issue by georgevanvliet** [beepnl/BEEP#21]
Please have collection endpoints, such as `GET /api/devices` return an empty array if the collection is empty, and make sure the http response code is also 200 OK.

Also have this behavior when applying query strings to collection endpoints e.g. `GET /api/devices?hardware_id`.

Currently endpoints, such as the one above, throw a 404 code and a string. This makes the client deserialization harder than necessary (invalid json, exception branching).

Current behavior for **non** collection endpoints such as `GET /api/devices/{id}` is fine as is (404).

**Comment by pvgennip** [comment]
This will break the current web app, because that depends on empty results having response code 404, so this would need a thorough refactoring.

**Comment by georgevanvliet** [comment]
Ok. I currently use custom error handling for all collection endpoints. It converts a 404 on collection endpoints to an empty array. It's dirty but it works for now.

**Comment by maartenvandillen** [comment]
I agree that this needs to be fixed. 404 means resource not found, but an empty collection is still a valid resource.
