### ISSUE TITLE
Internal server error when trying to create a sensor definition

### ISSUE THREAD

**Issue by georgevanvliet** [beepnl/BEEP#23]
When calling `POST /api/sensordefinition` with the following (minimal) body:
```
{"device_hardware_id":"0e0123f2a286a98aceee","offset":11,"multiplier":1,"input_measurement_abbreviation":"w_v"}
```
It works. But when doing the same with the following payload:
```
{"device_hardware_id":"0e0123f2a286a98aceee","offset":11,"multiplier":1,"input_measurement_abbreviation":"w_v","output_measurement_abbreviation":"weight_kg"}
```
 I get an internal server error:
```
LogicException: App\Measurement::pq_name must return a relationship instance. in file /opt/bitnami/apps/test.beep.nl/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 420
```

 The issue seems to be with the `output_measurement_abbreviation`. When adding this, the 500 appears. We discussed before that `weight_kg` is the appropriate value, and it worked before. I also checked the taxonomy if this value was present, just to be sure. But no go.

**Comment by pvgennip** [comment]
Error Solved
