### ISSUE TITLE
Change serialization of "inside" property on sensor definition

### ISSUE THREAD

**Issue by georgevanvliet** [beepnl/BEEP#25]
The documentation states that the "inside" property on sensordefinition is a bool. The api accepts both a number, a string, or a boolean. The response type from list sensordefinitions returns a number.

Please unify the typing to boolean in the response e.g. (see inside property)
```
  {
    "id": 78,
    "name": null,
    "inside": true,
    "offset": null,
    "multiplier": null,
    "input_measurement_id": 78,
    "output_measurement_id": null,
    "device_id": 125
  }
```

**Comment by pvgennip** [comment]
Solved
