### ISSUE TITLE
PATCH operations do not patch only the passed properties

### ISSUE THREAD

**Issue by georgevanvliet** [beepnl/BEEP#26]
When calling `PATCH /api/sensordefinition/{id}` with body:
```
{"device_hardware_id":"<REDACTED>", "inside":true,"name":"My first temp sensor"}
```
The result nullifies the properties that are not present. In particular the input output measurement types.

This is not the expected result on a PATCH operation (but PUT, maybe). It should only patch the properties that are passed, and leave the omitted properties to their current values.

**Comment by pvgennip** [comment]
Solved
