### ISSUE TITLE
Add proxy endpoints for TTN

### ISSUE THREAD

**Issue by georgevanvliet** [beepnl/BEEP#27]
Please add two endpoints that can be used for proxying to the TTN application manager:
* A `GET` for TTN devices: `http://eu.thethings.network:8084/applications/beep-digital-hive-monitoring/devices/<deviceId>`
* A `POST` for TTN devices: `http://eu.thethings.network:8084/applications/beep-digital-hive-monitoring/devices/<deviceId>`

The post receives the following payload:
```
{
  "dev_id": "<deviceId>",
  "lorawan_device": {
    "app_id": "beep-digital-hive-monitoring",
    "dev_eui": "<devEui>", 
    "dev_id": "<deviceId>", 
    "app_key": "<appKey>",
    "app_eui": "70B3D57ED0028D38" 
  }
}
```

**Comment by pvgennip** [comment]
Does the POST to TTN need to have the payload, or does the endpoint for POSTing to TTN (on the BEEP API) receive this payload?

**Comment by georgevanvliet** [comment]
Both. The devEui, appkey and deviceid are provided by the client. These should be used to (re)construct the above payload and pass it to ttn. Beep api should enforce proper appeui.

**Comment by pvgennip** [comment]
@georgevanvliet How can the client (app in this case) have knowledge of the <appKey>, shouldn't this be also enforced by the BEEP API settings?

**Comment by pvgennip** [comment]
This API calls can be tested (https://test.beep.nl/docs/#apidevicesttnhardwareid-get):
`GET api/devices/ttn/{hardware_id}`
`POST api/devices/ttn/{hardware_id}/dev_eui/{dev_eui}`

**Comment by georgevanvliet** [comment]
Ok works!
