### ISSUE TITLE
Edit existing Inspection creates a new Inspection

### ISSUE THREAD

**Issue by bogdanbrudiu** [beepnl/BEEP#39]
Click on Edit button of an inspection (https://app.beep.nl/webapp#!/hives/xxxx/inspections/xxxx)
Change Date of inspection and click Save Inspection

Expected: inspection is save with new date
Actual: a new inspection is created with the same data and the new date

**Comment by pvgennip** [comment]
@bogdanbrudiu This is a feature to copy an inspection with te same items filled to a new date :-)
If you want an empty inspection, use the 'New inspection' button in the inspection overview, or on the Apiary/Hive overview
