### ISSUE TITLE
Payload converter will not be supported in next release of TTN

### ISSUE THREAD

**Issue by avbentem** [beepnl/BEEP#43]
The next version of the TTN LoRaWAN Stack, V3, is due on the community network somewhere this year. As per https://www.thethingsnetwork.org/forum/t/convert-custom-payload-to-lpp-payload-in-ttn-console/12171/9:

> We’re dropping the converter and validator in V3 as they’re not being used; you can put conversion in the decoder, and it makes more sense to drop/filter out invalid values higher upstream.

And as per https://thethingsstack.io/v3.8.4/getting-started/migrating-from-v2/major-changes/

> ### Payload Formats
>
> The Things Network Stack V2 has support for payload decoders, converters, validators (for uplink) and encoders (for downlink). These can be either CayenneLPP or Javascript functions.
> 
> The Things Stack has support for an uplink payload formatter (similar to the payload decoder) and a downlink payload formatter (similar to the payload encoder). These can be set per application, and can even be overridden per end device. Similar to The Things Network Stack V2 , CayenneLPP and Javascript functions are supported.
> 
> Migrating the The Things Network Stack V2 payload encoder and decoder to an uplink and downlink payload formatter should be straightforward, since they have the same format.

So, it might be better to be prepared, and combine [ttn-payload-decoder.js](https://github.com/beepnl/BEEP/blob/master/ttn-payload-decoder.js) and [ttn-payload-converter.js](https://github.com/beepnl/BEEP/blob/master/ttn-payload-converter.js) into a single Decoder.

Better yet, maybe decoding should be done in the BEEP backend?

**Comment by pvgennip** [comment]
Thanks for this remark. We already have the converter and decoder in place in the BEEP backend, so we will switch to that soon.

**Comment by pvgennip** [comment]
Rolled out at live
