### ISSUE TITLE
Saving hive with feeding_box and queen_excluder layer in v3 results in 500 error

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#52]
For hives that already existed with those layer types (feeding_box & queen_excluder), the type has been renamed (to 'beelogger' and 'deutsch_normalmass_1_5').

So something seems to be going wrong with the hive layers, when the type is not brood or honey.

**Comment by pvgennip** [comment]
@JuliaBD I think this is a problem with the new local category database that you installed. For existing hives please select the right hive types and save them to correct this. Or remove all your apiaries and create new ones.
