### ISSUE TITLE
Inspection -> Top photo analysis: maximum values of the steppers incorrect

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#54]
On the inspection frontend, the maximum values of the top photo analysis brood layer & frames steppers are 2 and 11, instead of 5 and 20.

Maybe the max values are somehow overwritten by the lieberfelder template because of ng-show instead of ng-if in checklist_fieldset.html?

**Comment by pvgennip** [comment]
Fixed and released on app.beep.nl
