### ISSUE TITLE
When editing an inspection make sure colony_size value is not overwritten when hive properties change

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#56]
For inspections including colony size calculations (via top photo analysis or liebefelder method):
When hive properties (frames, brood/honey layers) change, the input values for colony_size change, and therefore the colony_size is recalculated. This also happens when editing an inspection where colony_size has previously been calculated, even if you don't want to edit the colony_size. The recalculated colony_size value will be saved when saving the edited inspection, which is undesirable.

Suggestion for solution:
Set the frame and layer values for colony_size calculation to 'null' by default. If these values are null, retrieve the colony_size value from the database (if existent) as colony_size value. As soon as the values are (re-)entered, the calculated value will be displayed instead.

**Comment by pvgennip** [comment]
Fixed, available on test and live
