### ISSUE TITLE
Add boolean checks for editing/creating inspections in inspect.html + editing hives in hive-edit.html

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#59]
Boolean checks should be as such for inspect.html:

-editing inspection only allowed when inspection.owner = true
-creating new inspection only allowed when hive.editable = true OR hive.owner = true

(in inspections.html these checks are already in place)

for hive-edit.html:

-editing hive only allowed when hive.editable = true OR hive.owner = true

**Comment by pvgennip** [comment]
Hive editing is only allowed if owner or editable.

Live on test and live server
