### ISSUE TITLE
Missing sensor constants in constants.js

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#63]
For example device 257 (Kast 1 - BEEPBASE-TEST-0E93) (s_bin_480_532) and device 60 (Test 3 - BEEPBASE-EBE9) (s_bin_0_201 to 1807_2008).

SOUND:

        's_bin_480_532',
        's_bin_0_201',
        's_bin_201_402',
        's_bin_402_602',
        's_bin_602_803',
        's_bin_803_1004',
        's_bin_1004_1205',
        's_bin_1205_1406',
        's_bin_1406_1607',
        's_bin_1607_1807',
        's_bin_1807_2008',

SENSOR_NAMES:
  
      s_bin_480_532: '480-532Hz',
        s_bin_0_201: '0-201Hz', 
        s_bin_201_402: '201-402Hz',
        s_bin_402_602: '402-602Hz',
        s_bin_602_803: '602-803Hz',
        s_bin_803_1004: '803-1004Hz',
        s_bin_1004_1205: '1004-1205Hz',
        s_bin_1205_1406: '1205-1406Hz',
        s_bin_1406_1607: '1406-1607Hz',
        s_bin_1607_1807: '1607-1807Hz',
        s_bin_1807_2008: '1807-2008Hz',

SENSOR_UNITS:

        s_bin_480_532: '',
        s_bin_0_201: '',
        s_bin_201_402: '',
        s_bin_402_602: '',
        s_bin_602_803: '',
        s_bin_803_1004: '',
        s_bin_1004_1205: '',
        s_bin_1205_1406: '',
        s_bin_1406_1607: '',
        s_bin_1607_1807: '',
        s_bin_1807_2008: '',

**Comment by pvgennip** [comment]
Solved on live and test
