### ISSUE TITLE
Handling email addresses with + characters

### ISSUE THREAD

**Issue by amotl** [beepnl/BEEP#7]
Dear @pvgennip,

just a quick note. When registering for an account with an email address like `username+extension@example.com`, we found that the form-prefill back on the login page you are redirected to after confirming the activation email would not honor plus characters (+) properly.

This yielded 
![image](https://user-images.githubusercontent.com/453543/59224048-b1db3300-8bcd-11e9-887e-4c1e9cc38231.png)
to us.

Just a convenience thing, not really a stopper bug.

Cheers,
Andreas.

**Comment by amotl** [comment]
The same thing happens on the password recovery dialog.

![image](https://user-images.githubusercontent.com/453543/65373940-59afd480-dc84-11e9-90ac-27f97ee32d14.png)

**Comment by pvgennip** [comment]
Sorry for late resolution, will be solved in next version (this month)
