### ISSUE TITLE
Fix typo in password-reset link

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#74]
Current link:

https://appv3.beep.nl/password-forgotc39a2cea8c2d73256c32b7b1b02031fe311be1d647135cb9de5484814ec12/?email=blabla@gmail.com

Should be:

https://appv3.beep.nl/password-reset?code=c39a2cea8c2d73256c32b7b1b02031fe311be1d647135cb9de5484814ec12&email=blabla@gmail.com

**Comment by pvgennip** [comment]
Done at test server

**Comment by JuliaBD** [comment]
It has been changed to password-reset but there were more typos:

Current link:

https://appv3.beep.nl/password-resetc39a2cea8c2d73256c32b7b1b02031fe311be1d647135cb9de5484814ec12/?email=blabla@gmail.com

Should be:

-start with '?code=' after 'password-reset'
-'&email=' instead of '/?email='

https://appv3.beep.nl/password-reset?code=c39a2cea8c2d73256c32b7b1b02031fe311be1d647135cb9de5484814ec12&email=blabla@gmail.com

**Comment by pvgennip** [comment]
Fixed on test
