### ISSUE TITLE
Allow user PATCH request for user locale update without password parameter

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#75]
Either make password not required when locale parameter is present, or make a different endpoint where user locale can be patched without password parameter.

**Comment by pvgennip** [comment]
Implemented and live on test server

**Comment by JuliaBD** [comment]
@pvgennip I still get "invalid_password" errors

**Comment by JuliaBD** [comment]
reopen

**Comment by pvgennip** [comment]
Fixed.
