### ISSUE TITLE
Raathoning boolean category item should not have a unit (kg) or it should be null

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#79]
Raathoning (category id 702) is a boolean but also contains a unit value (kg), which is meaningless (and redundant because there is a separate 'Hoeveelheid' item (if Raathoning = yes) that holds the amount in kg).

In both v2 and v3, unit is always displayed if it's present, so for Raathoning the inspections overview now says 'Yes kg' and 'No kg'.

Solution: omit the unit prop for Raathoning, or give it value null

**Comment by pvgennip** [comment]
@mato74 Can you please change this in the categorisation tree?

**Comment by mato74** [comment]
changed: removed physical quantity (kg) on 'comb honey' and added it on 'amount'
