### ISSUE TITLE
Implement Alerts in API

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#80]
**alert rule format:**
```
{
  id: int,
  name: string,
  description: string,
  measurement: string, (physical quantity + unit (see sensor definitions input and output))
  active hours: int array,
  active months: int array,
  period: int, (in minutes?) (select from minimum refresh time (retrieve from device) (in minutes?) or X, Y, Z hours)
  number of times: int,
  calculation: string, (min, max, av, der)
  comparator: string, (=, <, >, <=, >=)
  comparison function: string, (value, delta, abs value, abs delta)
  value: float,
  active: boolean
}
```

**alert format:**
```
{
  id, (needed for the PATCH request to toggle the 'show' boolean?)
  timestamp ('created_at'?),
  rule id,
  alert function,
  alert value (string array, easy to display if multiple values are present?),
  show, (boolean, default = true)
  device_id,
  device_name, (in case hive and/or device does not exist anymore)
  hive_id
}
```

**endpoints:**
GET alert rules
GET predefined alert rules
POST alert rule
GET alert
PATCH alert (to toggle the show boolean)

**Comment by pvgennip** [comment]
This will be implemented:
```
{
  id: int,
  name: string,
  description: string,
  measurement_id: int, (physical quantity + unit (see sensor definitions input and output))
  calculation: enum, (min, max, ave, der)
  calculation_minutes: int, (select from minimum refresh time (retrieve from device) or setting)
  comparator: enum, (=, <, >, <=, >=)
  comparison function: enum, (val, dif, abs, abs_dif)
  threshold_value: float,
  exclude_months: int array, (exclude, because a standard alert is 'always on') 
  exclude_hours: int array, (exclude, because a standard alert is 'always on') 
  alert_on_occurrences: int,
  alert_via_email: boolean,
  webhook_url: url, (optional endpoint to call for web hook integration)
  active: boolean
}
```

**Comment by pvgennip** [comment]
Implemented on test server

**Comment by rvaast** [comment]
Hi,

Where i can find the implémentation of this ?

**Comment by pvgennip** [comment]
@rvaast in branch: https://github.com/beepnl/BEEP/tree/vuejs-appv3

**Comment by rvaast** [comment]
Have you create an view for add rules or only use by api

**Comment by JuliaBD** [comment]
@pvgennip please default the int arrays (exclude_hive_ids, exclude_months & exclude_hours) to empty arrays [] when not filled. Currently they contain an empty string [""], which does not work well with the select box.

@rvaast we're currently creating a view for this for the new version of the app (v3).

**Comment by pvgennip** [comment]
@rvaast We are creating a VUE app in which we will create this view (see https://github.com/beepnl/beep-vue-app-legacy-api). Would you like to cooperate?

**Comment by rvaast** [comment]
@pvgennip if you want :) . I am not an expert in vue.js but i can watch. can you give me more details on the requirement (how do you expect things to be implemented) ? do you use slack or other to chat ?

**Comment by pvgennip** [comment]
@rvaast that would be great, I will invite you to our BEEP Slack.

**Comment by pvgennip** [comment]
Implemented at test and running evaluations
