### ISSUE TITLE
delete user SQL error

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#86]
500 error for user delete request:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`test_beep_nl`.`queens`, CONSTRAINT `queens_hive_id_foreign` FOREIGN KEY (`hive_id`) REFERENCES `hives` (`id`) ON UPDATE CASCADE) (SQL: delete from `users` where `id` = 49)

**Comment by pvgennip** [comment]
Solved in live and test
