### ISSUE TITLE
API update: change date of inspection instead of duplicating it

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#87]
currently, when editing the date of an existing inspection, it is duplicated (existing inspection is kept with the 'old' date, and a new inspection is created with the new date).

desired behaviour:
update the date of the existing inspection instead of duplicating it.

**Comment by pvgennip** [comment]
Please provide the inspection id (as id) in the list of parameters to edit the date of the inspection, in stead of creating a new inspection.

Live at test.beep.nl.
