### ISSUE TITLE
Temperature sensor cirkels

### ISSUE THREAD

**Issue by april-beep** [beepnl/BEEP#97]
BEEP base 6f30 heeft denk ik eerst 1 Temp sensor gehad (t_i), daarna overgestapt op 2. Dan zie je de ene T sensor er bij staan, aangezien ie dan op de achtergrond 2 nieuwe temperatuursensoren (t_0 en t_1) aanmaakt.
![Screen Shot 2021-04-22 at 11 40 52](https://user-images.githubusercontent.com/66108807/116389704-8e4f1f00-a81d-11eb-8f03-3dc756e4521f.png)

**Comment by pvgennip** [comment]
Fixed
